---
title: "broomtech"
author: "Aki"
date: "2020/7/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
library(broom)
data(iris)
```

```{r}
petalfit <- lm(Petal.Width ~ Petal.Length, iris)
```
```{r, fig.height = 3, fig.width = 5, fig.align = 'center'}
ggplot(iris) +
  geom_point(aes(x = Petal.Length,
                 y = Petal.Width,
                 group = Species,
                 color = Species),
             alpha = 0.7) +
  geom_abline(slope = petalfit$coefficients["Petal.Length"],
              intercept = petalfit$coefficients["(Intercept)"]
              ) + 
  theme_minimal() +
  theme(panel.grid = element_blank())
```

```{r}
summary(petalfit)
```

```{r}
broom::tidy(petalfit)
broom::augment(petalfit)
broom::glance(petalfit)
```
```{r, fig.height = 3, fig.width = 5, fig.align = 'center'}
ggplot() +
  geom_point(data = iris, aes(x = Petal.Length,
                 y = Petal.Width,
                 group = Species,
                 color = Species),
             alpha = 0.7) + 
  geom_point(data = broom::augment(petalfit),
             aes(x = Petal.Length,
                 y = .fitted)) + 
  theme_minimal() +
  theme(panel.grid = element_blank())
```
